package com.ittechoffice.example.model;

public class Table1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE1.COL1
     *
     * @mbg.generated Mon Oct 03 15:51:09 CST 2016
     */
    private String col1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TABLE1.COL2
     *
     * @mbg.generated Mon Oct 03 15:51:09 CST 2016
     */
    private String col2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE1.COL1
     *
     * @return the value of TABLE1.COL1
     *
     * @mbg.generated Mon Oct 03 15:51:09 CST 2016
     */
    public String getCol1() {
        return col1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE1.COL1
     *
     * @param col1 the value for TABLE1.COL1
     *
     * @mbg.generated Mon Oct 03 15:51:09 CST 2016
     */
    public void setCol1(String col1) {
        this.col1 = col1 == null ? null : col1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TABLE1.COL2
     *
     * @return the value of TABLE1.COL2
     *
     * @mbg.generated Mon Oct 03 15:51:09 CST 2016
     */
    public String getCol2() {
        return col2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TABLE1.COL2
     *
     * @param col2 the value for TABLE1.COL2
     *
     * @mbg.generated Mon Oct 03 15:51:09 CST 2016
     */
    public void setCol2(String col2) {
        this.col2 = col2 == null ? null : col2.trim();
    }
}