package com.ittechoffice.example.dao;

import com.ittechoffice.example.model.Table1;
import com.ittechoffice.example.model.Table1Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Table1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE1
     *
     * @mbg.generated Mon Oct 03 15:51:09 CST 2016
     */
    long countByExample(Table1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE1
     *
     * @mbg.generated Mon Oct 03 15:51:09 CST 2016
     */
    int deleteByExample(Table1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE1
     *
     * @mbg.generated Mon Oct 03 15:51:09 CST 2016
     */
    int insert(Table1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE1
     *
     * @mbg.generated Mon Oct 03 15:51:09 CST 2016
     */
    int insertSelective(Table1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE1
     *
     * @mbg.generated Mon Oct 03 15:51:09 CST 2016
     */
    List<Table1> selectByExample(Table1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE1
     *
     * @mbg.generated Mon Oct 03 15:51:09 CST 2016
     */
    int updateByExampleSelective(@Param("record") Table1 record, @Param("example") Table1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE1
     *
     * @mbg.generated Mon Oct 03 15:51:09 CST 2016
     */
    int updateByExample(@Param("record") Table1 record, @Param("example") Table1Example example);
}