
public interface ${javaClassName}Dao {

	public List<${javaClassName}> search(${javaClassName}Criteria ${uncaptialJavaClassName}Criteria);
	public ${javaClassName} find(${javaClassName}Key ${uncaptialJavaClassName}Key);
	public int insert(${javaClassName} ${uncaptialJavaClassName});
	public int update(${javaClassName} ${uncaptialJavaClassName});
	public int delete(${javaClassName}Key ${uncaptialJavaClassName}Key);
	
}