package com.ittechoffice.example.dao;

import com.ibatis.dao.client.DaoManager;
import com.ibatis.dao.client.template.SqlMapDaoTemplate;
import com.ittechoffice.example.model.Table1;
import com.ittechoffice.example.model.Table1Example;
import java.util.List;

public class Table1DAOImpl extends SqlMapDaoTemplate implements Table1DAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE1
     *
     * @mbg.generated Wed Nov 02 09:41:33 CST 2016
     */
    public Table1DAOImpl(DaoManager daoManager) {
        super(daoManager);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE1
     *
     * @mbg.generated Wed Nov 02 09:41:33 CST 2016
     */
    public long countByExample(Table1Example example) {
        Long count = (Long)  queryForObject("TABLE1.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE1
     *
     * @mbg.generated Wed Nov 02 09:41:33 CST 2016
     */
    public int deleteByExample(Table1Example example) {
        int rows = delete("TABLE1.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE1
     *
     * @mbg.generated Wed Nov 02 09:41:33 CST 2016
     */
    public void insert(Table1 record) {
        insert("TABLE1.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE1
     *
     * @mbg.generated Wed Nov 02 09:41:33 CST 2016
     */
    public void insertSelective(Table1 record) {
        insert("TABLE1.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE1
     *
     * @mbg.generated Wed Nov 02 09:41:33 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<Table1> selectByExample(Table1Example example) {
        List<Table1> list = queryForList("TABLE1.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE1
     *
     * @mbg.generated Wed Nov 02 09:41:33 CST 2016
     */
    public int updateByExampleSelective(Table1 record, Table1Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = update("TABLE1.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TABLE1
     *
     * @mbg.generated Wed Nov 02 09:41:33 CST 2016
     */
    public int updateByExample(Table1 record, Table1Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = update("TABLE1.updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TABLE1
     *
     * @mbg.generated Wed Nov 02 09:41:33 CST 2016
     */
    protected static class UpdateByExampleParms extends Table1Example {
        private Object record;

        public UpdateByExampleParms(Object record, Table1Example example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}