CREATE TABLE IF NOT EXISTS STUDENT (
	ID INT, NAME VARCHAR2, DESC VARCHAR2
);

INSERT INTO STUDENT(ID, NAME, DESC) VALUES (1, 'NAME 1', 'DESC 1');
INSERT INTO STUDENT(ID, NAME, DESC) VALUES (2, 'NAME 1', 'DESC 1');
INSERT INTO STUDENT(ID, NAME, DESC) VALUES (3, 'NAME 1', 'DESC 1');
INSERT INTO STUDENT(ID, NAME, DESC) VALUES (4, 'NAME 1', 'DESC 1');
INSERT INTO STUDENT(ID, NAME, DESC) VALUES (5, 'NAME 1', 'DESC 1');
INSERT INTO STUDENT(ID, NAME, DESC) VALUES (6, 'NAME 1', 'DESC 1');
INSERT INTO STUDENT(ID, NAME, DESC) VALUES (7, 'NAME 1', 'DESC 1');
INSERT INTO STUDENT(ID, NAME, DESC) VALUES (8, 'NAME 1', 'DESC 1');
INSERT INTO STUDENT(ID, NAME, DESC) VALUES (9, 'NAME 1', 'DESC 1');
INSERT INTO STUDENT(ID, NAME, DESC) VALUES (10, 'NAME 1', 'DESC 1');
INSERT INTO STUDENT(ID, NAME, DESC) VALUES (11, 'NAME 1', 'DESC 1');
INSERT INTO STUDENT(ID, NAME, DESC) VALUES (12, 'NAME 1', 'DESC 1');
INSERT INTO STUDENT(ID, NAME, DESC) VALUES (13, 'NAME 1', 'DESC 1');
INSERT INTO STUDENT(ID, NAME, DESC) VALUES (14, 'NAME 1', 'DESC 1');
INSERT INTO STUDENT(ID, NAME, DESC) VALUES (15, 'NAME 1', 'DESC 1');
