package com.ittechoffice.example;
// Generated 2016/10/3 ¤U¤È 04:25:22 by Hibernate Tools 5.2.0.Beta1

/**
 * TestEntity generated by hbm2java
 */
public class TestEntity implements java.io.Serializable {

	private Integer id;
	private String name;
	private String desc;

	public TestEntity() {
	}

	public TestEntity(String name, String desc) {
		this.name = name;
		this.desc = desc;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

}
