/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_techoffice_example_JniCaller */

#ifndef _Included_com_techoffice_example_JniCaller
#define _Included_com_techoffice_example_JniCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_techoffice_example_JniCaller
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_techoffice_example_JniCaller_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
