CREATE OR REPLACE FUNCTION GET_SEARCH_CONDITION(
   P_OWNER          VARCHAR2,
   P_CONSTRAINT_NAME  VARCHAR2
)
  RETURN VARCHAR2
IS 
  V_LONG LONG;
BEGIN
    SELECT 
        SEARCH_CONDITION 
    INTO V_LONG
    FROM USER_CONSTRAINTS 
    WHERE CONSTRAINT_NAME = P_CONSTRAINT_NAME
        AND OWNER = P_OWNER
    ;
    
    RETURN SUBSTR(V_LONG, 1, 32760 );
END;