CREATE OR REPLACE VIEW TABLE_META AS
SELECT 
    TAB_COL.COLUMN_ID,
    TAB_COL.TABLE_NAME, 
    TAB_COL.COLUMN_NAME,
    DATA_TYPE,
    NULLABLE,
    DATA_LENGTH,
    DECODE(DATA_SCALE, NULL, 999, DATA_SCALE) DATA_SCALE,
    (SELECT 1 FROM USER_CONS_COLUMNS CON_COL, USER_CONSTRAINTS CONS
        WHERE CON_COL.CONSTRAINT_NAME = CONS.CONSTRAINT_NAME
        AND CONS.CONSTRAINT_TYPE = 'P'
        AND TAB_COL.TABLE_NAME = CON_COL.TABLE_NAME
        AND TAB_COL.COLUMN_NAME = CON_COL.COLUMN_NAME) P_KEY
FROM 
USER_TAB_COLS TAB_COL
ORDER BY TAB_COL.COLUMN_ID
;
