CREATE TABLE TABLE1 (
	COL1 VARCHAR2, COL2 VARCHAR2, COL3 NUMBER
);

DELETE TABLE1;

INSERT INTO TABLE1 VALUES ('Testing 1', 'Testing 1', 1);
INSERT INTO TABLE1 VALUES ('Testing 2', 'Testing 2', 2);
INSERT INTO TABLE1 VALUES ('Testing 3', 'Testing 3', 3);